### PR TITLE
Don't hardcode .js suffixes, allow any

### PR DESCRIPTION
**Pull request by heldinz**
Making a pull request to allow other suffixes than .js on test files (eg .jsx in my case).

### CODE REVIEW

**Comment by pghalliday** [comment]
Cool thanks. I'll release this when I get home

**Comment by heldinz** [comment]
Great, thanks!

**Comment by pghalliday** [comment]
sorry for the delay, just published in version 0.1.3

**Comment by heldinz** [comment]
Cheers!

**Pull request merged**
